fix: Fix generateStacitParams in [board]/page.tsx
소괄호로 객체를 감싸는 것을 깜빡해서 에러가 발생
generateStaticParams가 제대로 된 배열을 반환하지 않으니
빌드 시 아래 에러 메시지가 뜸

Error: Page "/blog/[board]" is missing "generateStaticParams()"
so it cannot be used with "output: export" config.